### ISSUE TITLE
reader :UnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 3: invalid start byte

### ISSUE THREAD

**Issue by silenceper** [aliyun/aliyun-odps-python-sdk#10]
我有个odps 中的字段string中存放是BINARY类型(从mysql同步的)

在使用open_record_reader 中获取数据报错
```
        with download_session.open_record_reader(0,download_session.count) as reader:
            for record in reader:
```

traceback:
```
Traceback (most recent call last):
  ...........

    for record in reader:
  File "/Users/silenceper/Library/Python/2.7/lib/python/site-packages/odps/tunnel/tabletunnel/reader.py", line 168, in __next__
    record = self.read()
  File "/Users/silenceper/Library/Python/2.7/lib/python/site-packages/odps/tunnel/tabletunnel/reader.py", line 142, in read
    val = utils.to_text(self._reader.read_string())
  File "/Users/silenceper/Library/Python/2.7/lib/python/site-packages/odps/utils.py", line 266, in to_text
    return binary.decode(encoding)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 3: invalid start byte
```

**Comment by chineking** [comment]
OK，我们看下binary的数据如何处理。

**Comment by silenceper** [comment]
这个问题有解决的思路么？或者你们有啥建议

**Comment by chineking** [comment]
这个问题目前还不好解，因为我们没有一个类型表示是Binary。
目前MaxCompute正在做hive类型兼容，到时候会有binary类型。

目前要解比较麻烦，只能继承TableTunnelReader，重载read方法，遇到string类型不做转成str的操作。

还有没有更好的解决方案，我们再考虑下。

**Comment by chineking** [comment]
现在增加了 `options.tunnel.string_as_binary` 选项，设置为True，所有的字段将使用 bytes 读取，而不再尝试 decode 成 unicode。

**Comment by chineking** [comment]
先close，有问题随时reopen
