### ISSUE TITLE
unknown exception

### ISSUE THREAD

**Issue by Matiz7** [aliyun/aliyun-odps-python-sdk#12]
像是环境问题，同一份代码在另一台机器上运行正常，这台机器python3.5/2.7.13试过都有这问题 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests-2.12.4-py3.5.egg/requests/utils.py", line 792, in check_header_validity
    if not pat.match(value):
TypeError: expected string or bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test_aliyun_mc.py", line 55, in <module>
    UploadData()
  File "./test_aliyun_mc.py", line 18, in UploadData
    upload_session = tunnel.create_upload_session(table.name) #, partition_spec='pt=test')
  File "/usr/local/lib/python3.5/site-packages/pyodps-0.5.6-py3.5.egg/odps/tunnel/tabletunnel/tabletunnel.py", line 92, in create_upload_session
    compress_option=compress_option)
  File "/usr/local/lib/python3.5/site-packages/pyodps-0.5.6-py3.5.egg/odps/tunnel/tabletunnel/uploadsession.py", line 60, in __init__
    self._init()
  File "/usr/local/lib/python3.5/site-packages/pyodps-0.5.6-py3.5.egg/odps/tunnel/tabletunnel/uploadsession.py", line 74, in _init
    resp = self._client.post(url, {}, params=params, headers=headers)
  File "/usr/local/lib/python3.5/site-packages/pyodps-0.5.6-py3.5.egg/odps/rest.py", line 115, in post
    return self.request(url, 'post', data=data, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/pyodps-0.5.6-py3.5.egg/odps/rest.py", line 94, in request
    prepared_req = req.prepare()
  File "/usr/local/lib/python3.5/site-packages/requests-2.12.4-py3.5.egg/requests/models.py", line 257, in prepare
    hooks=self.hooks,
  File "/usr/local/lib/python3.5/site-packages/requests-2.12.4-py3.5.egg/requests/models.py", line 303, in prepare
    self.prepare_headers(headers)
  File "/usr/local/lib/python3.5/site-packages/requests-2.12.4-py3.5.egg/requests/models.py", line 427, in prepare_headers
    check_header_validity(header)
  File "/usr/local/lib/python3.5/site-packages/requests-2.12.4-py3.5.egg/requests/utils.py", line 796, in check_header_validity
    "not %s" % (value, type(value)))
requests.exceptions.InvalidHeader: Header value 0 must be of type str or bytes, not <class 'int'>

**Comment by chineking** [comment]
这个是requests新版的问题。

把pyodps更新上去应该就没有这个问题了。

pip install -U pyodps

**Comment by Matiz7** [comment]
[root@mysql-137 macscan]# python
Python 2.7.13 (default, Dec 19 2016, 09:51:10)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import odps
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/odps/__init__.py", line 37, in <module>
    from .utils import write_log as log
ImportError: cannot import name write_log
版本更新有点快 现在最新的是pyodps-0.6.6 ？

**Comment by chineking** [comment]
最新是0.6.6

```
pip install -U pyodps[full]
```

试下

**Comment by Matiz7** [comment]
内网机器，没法用pip，都是下源码安装的，上面那就是报的错误信息
import odps
Traceback (most recent call last):
File "", line 1, in 
File "/usr/local/lib/python2.7/site-packages/odps/init.py", line 37, in 
from .utils import write_log as log
ImportError: cannot import name write_log

**Comment by chineking** [comment]
这个错误……几乎没有有用信息呀。

到/usr/local/lib/python2.7/site-packages/odps/ 下，应该能看到utils.py文件，里面应该有write_log

**Comment by Matiz7** [comment]
是有这个函数，搞不懂
python2.7.13先装了pyodps-0.5.6.   然后又装了新下载的aliyun-odps-python-sdk-master （这个是0.6.6）
环境搞乱掉了

**Comment by chineking** [comment]
估计是之前的没清理干净，把安装的都卸载掉再安装把。

pip uninstall pyodps

没有网络pip也是可以卸载东西的。

**Comment by Matiz7** [comment]
是这个问题，现在都OK了
[root@mysql-137 pip-9.0.1]# pip uninstall pyodps
Uninstalling pyodps-0.6.6:
  /usr/local/lib/python2.7/site-packages/odps
  /usr/local/lib/python2.7/site-packages/pyodps-0.6.6-py2.7.egg-info
Proceed (y/n)? y
  Successfully uninstalled pyodps-0.6.6
[root@mysql-137 pip-9.0.1]# pip uninstall pyodps
Uninstalling pyodps-0.5.6:
  /usr/local/bin/pyou
  /usr/local/lib/python2.7/site-packages/pyodps-0.5.6-py2.7.egg
Proceed (y/n)? y
  Successfully uninstalled pyodps-0.5.6
[root@mysql-137 pip-9.0.1]# pip uninstall pyodps
Cannot uninstall requirement pyodps, not installed
