### ISSUE TITLE
[BUG] 如果o.get_table中表名和空间名为空，代码抛错一直在循环

### ISSUE THREAD

**Issue by daidai21** [aliyun/aliyun-odps-python-sdk#154]
后边有操作 `o.schema.columns` 获取列名

```sh
Traceback (most recent call last):
  File "<pyodps_user_code>", line 306, in <module>
    if "ds" not in get_table_column_name_lst(input_table_lst[i]):
  File "<pyodps_user_code>", line 127, in get_table_column_name_lst
    df = DataFrame(o.get_table(tab_name))
  File "/home/tops/lib/python3.7/site-packages/odps/df/core.py", line 91, in __init__
    kwargs['_schema'] = odps_schema_to_df_schema(data.schema)
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 226, in __getattribute__
    return super(Table, self).__getattribute__(attr)
  File "/home/tops/lib/python3.7/site-packages/odps/models/core.py", line 124, in __getattribute__
    self.reload()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 201, in reload
    self.schema.load()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 226, in __getattribute__
    return super(Table, self).__getattribute__(attr)
  File "/home/tops/lib/python3.7/site-packages/odps/models/core.py", line 124, in __getattribute__
    self.reload()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 201, in reload
    self.schema.load()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 226, in __getattribute__
    return super(Table, self).__getattribute__(attr)
  File "/home/tops/lib/python3.7/site-packages/odps/models/core.py", line 124, in __getattribute__
    self.reload()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 201, in reload
    self.schema.load()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 226, in __getattribute__
    return super(Table, self).__getattribute__(attr)
  File "/home/tops/lib/python3.7/site-packages/odps/models/core.py", line 124, in __getattribute__
    self.reload()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 201, in reload
    self.schema.load()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 226, in __getattribute__
    return super(Table, self).__getattribute__(attr)
  File "/home/tops/lib/python3.7/site-packages/odps/models/core.py", line 124, in __getattribute__
    self.reload()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 201, in reload
    self.schema.load()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 226, in __getattribute__
    return super(Table, self).__getattribute__(attr)
  File "/home/tops/lib/python3.7/site-packages/odps/models/core.py", line 124, in __getattribute__
    self.reload()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 201, in reload
    self.schema.load()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 226, in __getattribute__
    return super(Table, self).__getattribute__(attr)
  File "/home/tops/lib/python3.7/site-packages/odps/models/core.py", line 124, in __getattribute__
    self.reload()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 201, in reload
    self.schema.load()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 226, in __getattribute__
    return super(Table, self).__getattribute__(attr)
  File "/home/tops/lib/python3.7/site-packages/odps/models/core.py", line 124, in __getattribute__
    self.reload()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 201, in reload
    self.schema.load()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 226, in __getattribute__
    return super(Table, self).__getattribute__(attr)
  File "/home/tops/lib/python3.7/site-packages/odps/models/core.py", line 124, in __getattribute__
    self.reload()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 201, in reload
    self.schema.load()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 226, in __getattribute__
    return super(Table, self).__getattribute__(attr)
  File "/home/tops/lib/python3.7/site-packages/odps/models/core.py", line 124, in __getattribute__
    self.reload()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 201, in reload
    self.schema.load()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 226, in __getattribute__
    return super(Table, self).__getattribute__(attr)
  File "/home/tops/lib/python3.7/site-packages/odps/models/core.py", line 124, in __getattribute__
    self.reload()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 201, in reload
    self.schema.load()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 226, in __getattribute__
    return super(Table, self).__getattribute__(attr)
  File "/home/tops/lib/python3.7/site-packages/odps/models/core.py", line 124, in __getattribute__
    self.reload()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 201, in reload
    self.schema.load()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 226, in __getattribute__
    return super(Table, self).__getattribute__(attr)
  File "/home/tops/lib/python3.7/site-packages/odps/models/core.py", line 124, in __getattribute__
    self.reload()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 201, in reload
    self.schema.load()
  File "/home/tops/lib/python3.7/site-packages/odps/models/table.py", line 226, in __getattribute__
    return super(Table, self).__getattribute__(attr)
  File "/home/tops/lib/python3.7/site-packages/odps/models/core.py", line 124, in __getattribute__
    self.reload()
```

**Comment by wjsi** [comment]
Fixed in v0.11.3. Thanks for the report.
