### ISSUE TITLE
程序在win10上经常出现异常

### ISSUE THREAD

**Issue by Matiz7** [aliyun/aliyun-odps-python-sdk#17]
同一个程序在linux上运行正常，但在win10上经常在这出现异常
record = table.new_record([。。。。])
writer.write(record)

Traceback (most recent call last):
  File ".\test_aliyun_mc.py", line 71, in <module>
    UploadData()
  File ".\test_aliyun_mc.py", line 57, in UploadData
    skipped += 1
  File "F:\Python27\lib\site-packages\odps\tunnel\io\writer.py", line 234, in __exit__
    self.close()
  File "F:\Python27\lib\site-packages\odps\tunnel\io\writer.py", line 276, in close
    super(RecordWriter, self).close()
  File "F:\Python27\lib\site-packages\odps\tunnel\io\writer.py", line 227, in close
    super(BaseRecordWriter, self).close()
  File "F:\Python27\lib\site-packages\odps\tunnel\io\writer.py", line 67, in close
    self.flush_all()
  File "F:\Python27\lib\site-packages\odps\tunnel\io\writer.py", line 70, in flush_all
    self.flush()
  File "F:\Python27\lib\site-packages\odps\tunnel\io\writer.py", line 62, in flush
    self._output.write(data)
  File "F:\Python27\lib\site-packages\odps\tunnel\io\stream.py", line 82, in write
    raise_exc(ex_type, ex_value, tb)
  File "F:\Python27\lib\site-packages\odps\lib\lib_utils.py", line 98, in raise_exc
    six.exec_('raise ex_type, ex, tb', glb, locals())
  File "F:\Python27\lib\site-packages\odps\lib\six.py", line 719, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "F:\Python27\lib\site-packages\odps\tunnel\io\stream.py", line 51, in async_func
    self._resp = post_call(self.data_generator())
  File "F:\Python27\lib\site-packages\odps\tunnel\tabletunnel.py", line 258, in upload
    self._client.put(url, data=data, params=params, headers=headers)
  File "F:\Python27\lib\site-packages\odps\rest.py", line 128, in put
    return self.request(url, 'put', data=data, **kwargs)
  File "F:\Python27\lib\site-packages\odps\rest.py", line 107, in request
    proxies=self._proxy)
  File "F:\Python27\lib\site-packages\requests\sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "F:\Python27\lib\site-packages\requests\adapters.py", line 488, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: [Errno 10054]

**Comment by lyman** [comment]
看起来是这个？
https://support.microsoft.com/en-us/help/981344/an-application-may-receive-the-10054-error-when-the-application-receives-data-from-a-connection-on-a-computer-that-is-running-windows-7-or-windows-server-2008-r2-if-a-tdi-filter-driver-is-installed

**Comment by chineking** [comment]
先close，再次遇到问题再reopen。
