### ISSUE TITLE
数据上传时日期时间格式  缺少to_timestamp方法

### ISSUE THREAD

**Issue by Linuxsec** [aliyun/aliyun-odps-python-sdk#2]
/Users/tux/.pyenv/versions/2.7.10/bin/python2.7 /Users/tux/projects/python/other/Aliyun/AliyunODPS/test.py
Traceback (most recent call last):
  File "/Users/tux/projects/python/other/Aliyun/AliyunODPS/test.py", line 22, in <module>
    record = tb.new_record([1, 'daixijun', 'hashpassword', 20, True, datetime.now(), datetime.now()])
  File "/Users/tux/github/aliyun-odps-python-sdk/odps/models/table.py", line 479, in new_record
    return types.Record(schema=self.schema, values=values)
  File "/Users/tux/github/aliyun-odps-python-sdk/odps/types.py", line 358, in __init__
    self._sets(values)
  File "/Users/tux/github/aliyun-odps-python-sdk/odps/types.py", line 380, in _sets
    [self._set(i, value) for i, value in enumerate(values)]
  File "/Users/tux/github/aliyun-odps-python-sdk/odps/types.py", line 369, in _set
    val = validate_value(value, data_type)
  File "/Users/tux/github/aliyun-odps-python-sdk/odps/types.py", line 868, in validate_value
    data_type.validate_value(res)
  File "/Users/tux/github/aliyun-odps-python-sdk/odps/types.py", line 622, in validate_value
    timestamp = self.to_timestamp(val)
AttributeError: 'Datetime' object has no attribute 'to_timestamp'

Process finished with exit code 1

**Comment by chineking** [comment]
已经修复这个问题。`pip install --upgrade pyodps`再试一下。

**Comment by Linuxsec** [comment]
已经升级 测试OK
