### ISSUE TITLE
写数据时报错 AttributeError: 'memoryview' object has no attribute 'encode'

### ISSUE THREAD

**Issue by tongyifan** [aliyun/aliyun-odps-python-sdk#204]
pyodps: 0.11.3.1
requests: 2.30.0

在写数据时报错，但降级requests至2.28.2问题未再现
```
Traceback (most recent call last):
  File "main.py", line 195, in write_odps
    DataFrameODPS(data).persist(table_name, partition=partition_keys, drop_table=True, odps=o,
  File "/usr/local/lib/python3.8/dist-packages/odps/df/expr/expressions.py", line 43, in __call__
    return self._func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/odps/df/expr/expressions.py", line 266, in persist
    return self._handle_delay_call('persist', self, name, partitions=partitions, partition=partition,
  File "/usr/local/lib/python3.8/dist-packages/odps/df/expr/expressions.py", line 43, in __call__
    return self._func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/odps/df/expr/expressions.py", line 158, in _handle_delay_call
    result = getattr(engine, method)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/odps/df/backends/core.py", line 741, in persist
    return self._action(*exprs_args_kwargs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/odps/df/backends/core.py", line 555, in _action
    res = self._execute_dag(dag, ui=ui, async_=async_, n_parallel=n_parallel,
  File "/usr/local/lib/python3.8/dist-packages/odps/df/backends/core.py", line 799, in _execute_dag
    return dag.execute(ui=ui, async_=async_, n_parallel=n_parallel, timeout=timeout,
  File "/usr/local/lib/python3.8/dist-packages/odps/df/backends/core.py", line 338, in execute
    results = self._run(ui, progress_proportion)
  File "/usr/local/lib/python3.8/dist-packages/odps/df/backends/core.py", line 212, in _run
    res = call(ui=ui, progress_proportion=progress_proportion / len(calls))
  File "/usr/local/lib/python3.8/dist-packages/odps/df/backends/core.py", line 191, in __call__
    res = self.run(ui=ui, progress_proportion=progress_proportion)
  File "/usr/local/lib/python3.8/dist-packages/odps/df/backends/core.py", line 691, in run
    result = engine._do_persist(expr_dag, expr, name, **kw)
  File "/usr/local/lib/python3.8/dist-packages/odps/df/backends/pd/engine.py", line 61, in wrapped
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/odps/df/backends/pd/engine.py", line 359, in _do_persist
    write_table(df, t, ui=ui, cast=cast, overwrite=overwrite, partitions=partitions, partition=partition,
  File "/usr/local/lib/python3.8/dist-packages/odps/df/backends/utils.py", line 251, in write_table
    _write_table_no_partitions(frame, table, ui, cast=cast, overwrite=overwrite, partition=partition,
  File "/usr/local/lib/python3.8/dist-packages/odps/df/backends/utils.py", line 209, in _write_table_no_partitions
    writer.write(gen())
  File "/usr/local/lib/python3.8/dist-packages/odps/models/table.py", line 290, in __exit__
    self.close()
  File "/usr/local/lib/python3.8/dist-packages/odps/models/table.py", line 837, in close
    super(_RecordWriter, self).close()
  File "/usr/local/lib/python3.8/dist-packages/odps/models/table.py", line 271, in close
    writer.close()
  File "/usr/local/lib/python3.8/dist-packages/odps/tunnel/io/writer.py", line 355, in close
    self._req_io.finish()
  File "/usr/local/lib/python3.8/dist-packages/odps/tunnel/io/stream.py", line 121, in finish
    six.reraise(ex_type, ex_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/odps/lib/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/odps/tunnel/io/stream.py", line 76, in async_func
    self._resp = post_call(self.data_generator())
  File "/usr/local/lib/python3.8/dist-packages/odps/tunnel/tabletunnel.py", line 43, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/odps/tunnel/tabletunnel.py", line 342, in upload
    self._client.put(url, data=data, params=params, headers=headers)
  File "/usr/local/lib/python3.8/dist-packages/odps/rest.py", line 193, in put
    return self.request(url, 'put', data=data, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/odps/rest.py", line 168, in request
    res = self.session.send(prepared_req, stream=stream,
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 385, in _make_request
    conn.request_chunked(method, url, **httplib_request_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 226, in request_chunked
    chunk = chunk.encode("utf8")
AttributeError: 'memoryview' object has no attribute 'encode'
```

**Comment by wjsi** [comment]
Should not be a issue with v0.11.4.
