### ISSUE TITLE
_odps_type_to_sqlalchemy_type 类型转换出错

### ISSUE THREAD

**Issue by zhaoxuan** [aliyun/aliyun-odps-python-sdk#240]
在 superset 里面如果使用了 column 含有 json 类型的数据，在做类型转换会报错。
```
2024-07-22 09:10:32,232:ERROR:flask_appbuilder.api:<class 'odps.types.Json'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask_appbuilder/api/__init__.py", line 110, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 127, in wraps
    raise ex
  File "/app/superset/views/base_api.py", line 121, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/app/superset/utils/core.py", line 1463, in time_function
    response = func(*args, **kwargs)
  File "/app/superset/utils/log.py", line 255, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/databases/api.py", line 741, in table_metadata
    table_info = get_table_metadata(database, table_name, schema_name)
  File "/app/superset/databases/utils.py", line 67, in get_table_metadata
    columns = database.get_columns(table_name, schema_name)
  File "/app/superset/models/core.py", line 847, in get_columns
    return self.db_engine_spec.get_columns(
  File "/app/superset/db_engine_specs/base.py", line 1343, in get_columns
    cast(list[SQLAColumnType], inspector.get_columns(table_name, schema))
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 497, in get_columns
    col_defs = self.dialect.get_columns(
  File "/usr/local/lib/python3.10/site-packages/odps/sqlalchemy_odps.py", line 326, in get_columns
    col_type = _odps_type_to_sqlalchemy_type[type(col.type)]
KeyError: <class 'odps.types.Json'>
```

**Comment by wjsi** [comment]
Fixed with v0.11.6.2.
