### ISSUE TITLE
json串怎么并列多行输出？

### ISSUE THREAD

**Issue by shasky2014** [aliyun/aliyun-odps-python-sdk#90]
```
    df['schedule_lesson'] = df.apply(
        lambda row: union_lesson(row.unitids, row.unitlessonmap, row.scheduleconf),
        axis=1,
        reduce=True,
        types='string'
    ).rename('schedule_lesson')
# 自定义函数没法输出list，只能先用json.dumps转string,结果大致
# schedule_lesson = '''[[1,2,a],[1,3,a],[1,2,b]...]'''

# 最后要再explose，怎么做？，要是list可以直接这么搞，现在是string怎么搞？
    df[df.course_id,df.plan_id,df.schedule_lesson.explose()]
```

**Comment by chineking** [comment]
df.schedule_lesson.split(',').explode()

**Comment by shasky2014** [comment]
直接split不行，这个字符串是嵌套的数组结构

**Comment by shasky2014** [comment]
类似这样的方法有吗？
`df[df.course_id,df.plan_id,df.schedule_lesson.(lambda x: json.loads(x)).explose()]`

**Comment by shasky2014** [comment]
这个用不起来

**Comment by shasky2014** [comment]
在函数输出字符串时，控制分隔符了可以split了

**Comment by chineking** [comment]
explode

**Comment by shasky2014** [comment]
我把一列split的时候    `out_table['schedule'] = out_table.schedule_lesson.split(',')[0]`
报错如下，啥情况？


```python
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/pd/compiler.py:1034: FutureWarning: The reduce argument is deprecated and will be removed in a future version. You can specify result_type='reduce' to try to reduce the result to the original dimensions
  args=expr._func_args, **expr._func_kwargs)
Traceback (most recent call last):
  File "/Users/admin/PycharmProjects/PyodpsPro/etl/OdpsStat/dim_plan_lesson_schedule3.py", line 99, in <module>
    print(out_table.head(100))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/expr/expressions.py", line 43, in __call__
    return self._func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/expr/expressions.py", line 1058, in head
    return self._handle_delay_call('execute', self, head=n, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/expr/expressions.py", line 43, in __call__
    return self._func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/expr/expressions.py", line 146, in _handle_delay_call
    result = getattr(engine, method)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/core.py", line 734, in execute
    return self._action(*exprs_args_kwargs, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/core.py", line 557, in _action
    timeout=timeout, progress_proportion=progress_proportion)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/core.py", line 799, in _execute_dag
    close_and_notify=close_and_notify, progress_proportion=progress_proportion)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/core.py", line 339, in execute
    results = self._run(ui, progress_proportion)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/core.py", line 213, in _run
    res = call(ui=ui, progress_proportion=progress_proportion / len(calls))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/core.py", line 192, in __call__
    res = self.run(ui=ui, progress_proportion=progress_proportion)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/core.py", line 590, in run
    result = engine._do_execute(expr_dag, expr, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/pd/engine.py", line 58, in wrapped
    return fun(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/pd/engine.py", line 230, in _do_execute
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/pd/engine.py", line 88, in _run
    res = func(results)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/pd/compiler.py", line 1174, in handle
    result = result.join(f)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/frame.py", line 6326, in join
    rsuffix=rsuffix, sort=sort)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/frame.py", line 6341, in _join_compat
    suffixes=(lsuffix, rsuffix), sort=sort)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 61, in merge
    return op.get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 573, in get_result
    rdata.items, rsuf)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/internals.py", line 5244, in items_overlap_with_suffix
    '{rename}'.format(rename=to_rename))
ValueError: columns overlap but no suffix specified: Index(['schedule_lesson'], dtype='object')
```
