### ISSUE TITLE
一列变多列报错

### ISSUE THREAD

**Issue by shasky2014** [aliyun/aliyun-odps-python-sdk#91]
schedule_lesson='20180101,1,a'
out_table['schedule_type'] = out_table.schedule_lesson.split(',')[1]

报错如下
```
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/pd/compiler.py:1034: FutureWarning: The reduce argument is deprecated and will be removed in a future version. You can specify result_type='reduce' to try to reduce the result to the original dimensions
  args=expr._func_args, **expr._func_kwargs)
Traceback (most recent call last):
  File "/Users/admin/PycharmProjects/PyodpsPro/etl/OdpsStat/dim_plan_lesson_schedule3.py", line 106, in <module>
    print(out_table.head(100))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/expr/expressions.py", line 43, in __call__
    return self._func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/expr/expressions.py", line 1058, in head
    return self._handle_delay_call('execute', self, head=n, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/expr/expressions.py", line 43, in __call__
    return self._func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/expr/expressions.py", line 146, in _handle_delay_call
    result = getattr(engine, method)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/core.py", line 734, in execute
    return self._action(*exprs_args_kwargs, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/core.py", line 557, in _action
    timeout=timeout, progress_proportion=progress_proportion)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/core.py", line 799, in _execute_dag
    close_and_notify=close_and_notify, progress_proportion=progress_proportion)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/core.py", line 339, in execute
    results = self._run(ui, progress_proportion)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/core.py", line 213, in _run
    res = call(ui=ui, progress_proportion=progress_proportion / len(calls))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/core.py", line 192, in __call__
    res = self.run(ui=ui, progress_proportion=progress_proportion)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/core.py", line 590, in run
    result = engine._do_execute(expr_dag, expr, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/pd/engine.py", line 58, in wrapped
    return fun(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/pd/engine.py", line 230, in _do_execute
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/pd/engine.py", line 88, in _run
    res = func(results)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/odps/df/backends/pd/compiler.py", line 1174, in handle
    result = result.join(f)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/frame.py", line 6326, in join
    rsuffix=rsuffix, sort=sort)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/frame.py", line 6341, in _join_compat
    suffixes=(lsuffix, rsuffix), sort=sort)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 61, in merge
    return op.get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 573, in get_result
    rdata.items, rsuf)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/internals.py", line 5244, in items_overlap_with_suffix
    '{rename}'.format(rename=to_rename))
ValueError: columns overlap but no suffix specified: Index(['schedule_lesson'], dtype='object')
```

**Comment by chineking** [comment]
Github issue 不是用来提问的地方。先 close
